In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from word2number import w2n

In [3]:
df = pd.read_csv(r'/home/acts/Mohit/PGD-HPCSA/Machine Learning/Datasets/hiring.csv')
df.head()

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [9]:
for i in range(8):
    print(w2n.word_to_num(df.experience[i]))

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [7]:
df.count()

experience                    6
test_score(out of 10)         7
interview_score(out of 10)    8
salary($)                     8
dtype: int64

In [6]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000